### ISSUE TITLE
Comparison to xmldom

### ISSUE THREAD

**Issue by physikerwelt** [NaturalIntelligence/fast-xml-parser#134]
How does the performance of reading XML files compares to [xmldom](https://www.npmjs.com/package/xmldom)? Was this investigated?

**Comment by amitguptagwl** [comment]
`xmldom` is a dead project I guess. Because there is no update from last 2 years. So many PRs and issues are still open.

This is the benchmarking result for just parsing; Please note that performance of fxp will be higher when you'll not convert the XML to JS object but an intermediate object (XMLnode). However, converting to JS object give you the benefit of easy manipulation.

```
fxp : 87710.72546590598 requests/second
xmldom : 77285.7702536101 requests/second
```

I'll say that you should not compare both packages if you want to use DOM style manipulation.
```js
doc3.documentElement.appendChild(doc3.documentElement.lastChild);
```

But if you're fine to manipulate js objects directly then you don't need to compare them.
