### ISSUE TITLE
Question: Validating Output Of Parsing Xml Document

### ISSUE THREAD

**Issue by bhreinb** [NaturalIntelligence/fast-xml-parser#144]
Hi There,

I tried out your module to see whether it would be candidate library to use for automated testing of SOAP functionality. I detail my use case below with a sample file

```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:bsvc="urn:com.company/bsvc">
    <soapenv:Header>
        <bsvc:Company_Common_Header>
            <!--Optional:-->
            <bsvc:Include_Reference_Descriptors_In_Response>?</bsvc:Include_Reference_Descriptors_In_Response>
        </bsvc:Company_Common_Header>
    </soapenv:Header>
</soapenv:Envelope>
```
I load that xml via the following code....

```
const xml = parser.parse((readFileSync('./files/DeleteWorkerDocument.xml', 'utf8')), {attributeNamePrefix : "_", ignoreAttributes : false, ignoreNameSpace : false});
```
However, I'm returned the following JSON payload...

```
{
  "_xmlns:soapenv": "http://schemas.xmlsoap.org/soap/envelope/",
  "_xmlns:bsvc": "urn:com.company/bsvc",
  "soapenv:Header": {
    "bsvc:Company_Common_Header": {
      "bsvc:Include_Reference_Descriptors_In_Response": "?"
    }
  }
}
```
Just wondering when I send the same xml to this service for example `https://codebeautify.org/xmltojson` how come I get a different payload to above?

```
{
	"Envelope": {
		"Header": {
			"Company_Common_Header": {
				"Include_Reference_Descriptors_In_Response": {
					"__prefix": "bsvc",
					"__text": "?"
				},
				"__prefix": "bsvc"
			},
			"__prefix": "soapenv"
		},
		"_xmlns:soapenv": "http://schemas.xmlsoap.org/soap/envelope/",
		"_xmlns:bsvc": "urn:com.company/bsvc",
		"__prefix": "soapenv"
	}
}
```
The last result rendered is generally what I get returned back when I use an online service to validate the integrity of the payload as opposed to this library. The latter payload is something I'm seeing quite frequently across online sites. Thoughts? What's the reasons for the discrepancies?

**Comment by amitguptagwl** [comment]
@bhreinb Sorry if I'm rude but this is the 4th questions in last few days where I see no issue. Hence I'm making it compulsory to answer the questions that you see in issue template. I'll not be able to help on any issue further if this checklist is removed from the issue.


* [ ] Have you asked your question on Stackoverflow or similar forum?
* [ ] Are you running the latest version?
* [ ] Have you included sample input, output, error, and expected output? 
* [ ] Have you checked if you are using correct configuration?
* [ ] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

**Comment by bhreinb** [comment]
Hi @amitguptagwl 

Yes your right your answer is exceptionally rude. Considering I also do a bit of GitHub development too, I would not respond to another developer like you just did. I do understand where you coming from "somewhat" but I don't think your response needs to be as condescending as it is.

Btw four questions re your project regardless of it been noise or not should be considered a good thing as your project is considered good by the community. I think you should view that as a positive rather than a negative.

Apologies I didn't fill the template but the first open item in issues doesn't adhere to your "mandatory" template.

Re the suggested template (why I didn't fill it out) I'm benchmarking the integrity of the payload of the json your library generates against other online tools. I reference one in the original message. Other online services consistently produce the same.

So my "Question" re your library, which I think was fair as to why their was such a discrepancy? The only thing I didn't do was ask on stack overflow but when I'm seeing a consistent response from multiple sources in contrary to yours am I not entitled to query the integrity of what your library produces?

Have a nice day 🙂

**Comment by amitguptagwl** [comment]
Series of rude replies... :p apology to hurt you hard.

The reason I asked you to attach the checklist because the people who
raised last 2-3 issues didn't actually check the online tool. And I spent
approx 30mins for each issue to figure out that there was nothing wrong
with what they were doing. They just raised the issue before even checking
that they're doing everything right.

Jumping to your question, fxp actually returns one more root level element
so I've attached the output in my last comment. If you check with online
tool and ignore namespace, you'll find that the response is same. There is
only one difference that in other output the namespace renders as property
of the tag.

In my knowledge, there is no standard defined for that. Hence, all the
parsers parse it differently. However, if you feel that parsing it as a
property can be more appropriate, we can think to introduce a new config
option for that.

In last, I respect all the developers and love to solve their queries but
you can understand that I'm managing more than 20 repos on Github alone.
And I respond to all the issues and try to solve them within a day even if
it is a holiday. However, keep my response aside and keep working as
opensource developer.

All the best.

On 16 Feb 2019 7:22 am, "Bhréin Brannick" <notifications@github.com> wrote:

Hi @amitguptagwl <https://github.com/amitguptagwl>

Yes your right your answer is exceptionally rude. Considering I also do a
bit of GitHub development too, I would not respond to another developer
like you just did. I do understand where you coming from "somewhat" but I
don't think your response needs to be as condescending as it is.

Btw four questions re your project regardless of it been noise or not
should be considered a good thing as your project is considered good by the
community. I think you should view that as a positive rather than a
negative.

Apologies I didn't fill the template but the first open item in issues
doesn't adhere to your "mandatory" template.

Re the suggested template (why I didn't fill it out) I'm benchmarking the
integrity of the payload of the json your library generates against other
online tools. I reference one in the original message. Other online
services consistently produce the same.

So my "Question" re your library, which I think was fair as to why their
was such a discrepancy? The only thing I didn't do was ask on stack
overflow but when I'm seeing a consistent response from multiple sources in
contrary to yours am I not entitled to query the integrity of what your
library produces?

Have a nice day 🙂

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/NaturalIntelligence/fast-xml-parser/issues/144#issuecomment-464272197>,
or mute the thread

**Comment by bhreinb** [comment]
Hi @amitguptagwl 

I do understand your frustrations. I guess their is lessons for both of us from the thread. I possibly should have checked stackoverflow re opening an issue on your repo. I will post a question on that site in any case to get further clarity on this.

Yeah so when I tried your library through an API the payload matches the online tool.

Re handling the namespace i.e. renders as property of the tag that is the source of confusion for me, which was why I submitted this question. To me the way the library generates the payload makes more sense as it's more readable and condensed. However my use case is that folk within my team would load a yaml input file into a framework that can be exported to xml or json for testing a web service. We are considering yaml so to have a consistent experience across both but their may be cases where they need to convert from xml to yaml to fit the consistent experience as for example a particular web service could be defined in xml structure or vice versa. As part of that they are likely to use online tools to help them with that, hence the questioning re the discrepancies.

Perhaps if your ok with having a new config to accomodate that, this would be super helpful but let me follow up on stackoverflow.

Lastly 20 repos is very good. Keep up the good work 👍

**Comment by amitguptagwl** [comment]
Thanks for the appreciation. Probably you can help to maintain some ;) 

Since it'll be a new feature so you can stick here. I prefer people to go to Stackoverflow only for technical issues where this library is expected to return desire output but somehow people fail to get it. Or about how to use this library.

I see 2 features here

1. XML to YAML
2. XML to parser with namespace as property

A tag can have a namespace and attributes can also have different namespaces. So we may have to create an array of namespaces or will have to ignore namespace attached to attributes. But what is most important is the purpose of having the namespace. In my understanding, your testing utility is not gonna use the namespace.

I want to understand the actual need to render it as property which can happen in general with many projects.

**Comment by bhreinb** [comment]
The testing utility would need the namespace.

But it's likely I don't need it rendered as a property of a tag however.

Another possible solution which I think you are referencing above (as per feature 1) is the online tool could be evolved to "parse to YAML" which would be rendered to the output window?

**Comment by amitguptagwl** [comment]
> But it's likely I don't need it rendered as a property of a tag however.

So we don't need feature 2.
Yes, I'm suggesting "XML to YAML" as a new feature for this library. Though I'm not sure if people really need it, but it can be an experiment.

**Comment by bhreinb** [comment]
Don't think I need #2  as your library correctly generates the xml message regardless of how that is represented in a js object.

In terms of capturing xml to yaml in the online tool what is the way forward for this feature request. New issue?

**Comment by amitguptagwl** [comment]
Yeah will create the new issue for fresh discussion on that. But as I'm
running busy, I'll leave it to implement in the future.

General implementation should not take more than 2 days. But following all
the rules may take time

**Comment by bhreinb** [comment]
thanks a mill for this 👍
