### ISSUE TITLE
group children

### ISSUE THREAD

**Issue by guatedude2** [NaturalIntelligence/fast-xml-parser#159]
Is it possible to group children so that the structure looks more like the example bellow? If not how could I get a feature request?

given the XML:
```
<any_name>
    <person name="Jack Johnson" age="33">
        <address city="New York" state="NY" />
        <address city="Boston" state="MA" />
    </person>
</any_name>
```

Output:
```
{
  "type": "any_name",
  "children": [
    {
      "type": "person",
      "name": "Jack Johnson",
      "age": 33,
      "children": [
        {
          "type": "address",
          "city": "New York",
          "state": "NY"
        },
        {
          "type": "address",
          "city": "Boston",
          "state": "MA"
        }
      ]
    }
  ]
}
```

**Comment by amitguptagwl** [comment]
Currently, it is not supported. What I can see here is to generate the JSON schema directly from XML. I'll suggest to convert XML to json and the write a schema builder on top of that. Because there can be different ways to generate the schema for different application.

[Here](https://github.com/nimndata/nimnjs-schema-builder) is the sample repo that I build to create the JSON schema from the sample JSON file.

**Comment by guatedude2** [comment]
That's what I ended up doing. Thanks for your help
