### ISSUE TITLE
Add namespaces when transforming json to xml

### ISSUE THREAD

**Issue by mupakoz** [NaturalIntelligence/fast-xml-parser#161]
I would like to transform json to xml adding namespaces during the process. Example:

```js
const jsonObj = {
    someTag: "someTagText"
}
var xml = parser.parse(jsonObj);
```

Expected result:

```xml
<namespaceName:someTag>someTagText</namespaceName:someTag>
```
So far I did not find any way of doing it without adding the namespace before the transformation. However, it is troublesome for big objects. Is it a functionality that would fit in the library? Probably could be solved with something like a tagNameProcessor in the options

**Comment by amitguptagwl** [comment]
It's a good suggestion. I believe tagNameProcessor will be helpful. But how will you code inside? I mean there is a possibility that you want different namespace for the same tags inside different parent tag and other situations.

**Comment by Domvel** [comment]
In my case, I just want to remove the namespace when xml 2 json and re-add it for the xml export.
I have no idea how complex an XML namespace can be. Or how xml exactly works for this feature. I could write an own processor after parsing to json or before parsing to xml to remove and add the key (tag) prefixes.

I have the following input. (And later, my desired xml export)
```xml
<?xml version="1.0" encoding="UTF-8"?>
<foo:BAR xmlns:foo="about:blank" Version="1.2.3.4">
  <foo:Blah>
     ...
  </foo:Blah>
</foo>
```

I use `ignoreNameSpace` to access the keys by dot-notation (`json.bar`) instead of bracket notation (`json['foo:bar']`). It's prettier and more clean. (I use TypeScript.)

For the xml export a new option `namespaceName` could be usefull. Or `tagNameProcessor` as well.
Or I just add the Attribut `xmlns:foo` to the root node attribut and the exporter detects it and add the namespace automatically. (if not already set). 
I just think aloud. 🙂 

For now, I think I set `ignoreNameSpace` to `false` or I handle it with a own function.

**Comment by amitguptagwl** [comment]
@Domvel the main problem is we can have multiple namespaces and each tag, whether repeated or not, can be associated with a different namespace. Hence, it is not achievable without providing all the mappings ie XSD itself.

The main focus of this library is to avoid such complex parsing for the sake of speed.

Closing this thread. Feel free to reopen.
