### ISSUE TITLE
Parsing of large xmls (>100MB)

### ISSUE THREAD

**Issue by zWaR** [NaturalIntelligence/fast-xml-parser#195]
I noticed the documentation says library was tested with files up to 100MB. We're having files larger  than this ~160MB (+/-10MB). And we tried this approach:

```TypeScript
import { convertToJson, getTraversalObj, validate } from 'fast-xml-parser';

export class XmlParser implements XmlParserInterface {
  options = {
    attributeNamePrefix: '',
    attrNodeName: 'attr',
    textNodeName: '#text',
    ignoreAttributes: false,
    ignoreNameSpace: false,
    allowBooleanAttributes: false,
    parseNodeValue: true,
    parseAttributeValue: false,
    trimValues: true,
    cdataTagName: '__cdata',
    cdataPositionChar: '\\c',
    localeRange: '',
  };

  async getJson(sourceFile: string): Promise<any> {
    return new Promise<any>((resolve, reject) => {
      const xmlData = fs.readFileSync(sourceFile).toString();

      if (validate(xmlData) !== true) {
        return reject('Validation failed');
      }

      const parsedJson = convertToJson(getTraversalObj(xmlData, this.options), this.options);

      resolve(parsedJson);

    });
  }
}
```

The idea behind our approach is based on `large_spec.js`.

Unfortunately this approach breaks with memory allocation errors:

```
<--- Last few GCs --->

[31204:0x3539840]   109929 ms: Scavenge 1138.5 (1436.3) -> 1130.8 (1440.3) MB, 22.6 / 0.0 ms  (average mu = 0.066, current mu = 0.049) allocation failure
[31204:0x3539840]   111541 ms: Mark-sweep 1141.2 (1440.3) -> 1128.4 (1438.3) MB, 1563.6 / 0.0 ms  (average mu = 0.068, current mu = 0.070) allocation failure scavenge might not succeed
<--- JS stacktrace --->
```

We noticed that if we remove options, method does not break, however it also does not parse the attributes, which are needed for us. 
As mentioned, we realize officially you are supporting only files up to 100MB. However, is there any one who was able to parse larger files than that? And if so, do you have any tips? Is there something in the options we could tweak, add, remove? Any pointers would be appreciated!

Right now we're using version: 3.12.0

**Comment by amitguptagwl** [comment]
1. Someone reported that he tested the file up to 800 mb. And it was working fine. However, I don't what are the options he tried with.
2. Have you tried with just `ignoreAttributes: false`?
3. If you're processing such big files, the better option is to use the parser based on C/C++ libraries. As they would be faster.

Definitely, many changes have happened in the library after I checked it against a big XML file. However, the reason it doesn't work for long files because of the node js restriction for the regular expression. So you may also try it with a different version of node js.

Though I can change the library to process chunks and work perfectly fine for very big files, it'll slow it down. However, I'll try some options in the future.
