### ISSUE TITLE
Feature: Preserve position of elements

### ISSUE THREAD

**Issue by amitguptagwl** [NaturalIntelligence/fast-xml-parser#197]
For some processing purpose, it is requied to preserve the position of tags and text value of a tag. Eg
```xml
<store> locates in
        <region>US</region>
         and
        <region>Japan</region>
        only
</store>
```

currently parsed to following when arrayMode is true.
```json
{
    "store": [
        {
            "#text": "locates inandonly",
            "region": [
                "US",
                "Japan"
            ]
        }
    ]
}
```
The expected output is one of the following
```json
{
    "store": [
        { "#text": "locates in" },
        { "region": "US" },
        { "#text": "and" },
        { "region": "Japan" },
        { "#text": "only" }
    ]
}
```

```json
{
    "store": [
        "locates in",
        { "region": "US" },
        "and",
        { "region": "Japan" },
        "only"
    ]
}
```

**Comment by MaartenX** [comment]
As you can see, I added a pull request that adds this behavior. One thing I did not yet tackle was handling of CDATA blocks in text.

**Comment by samuelcolvin** [comment]
Thanks for the awesome library, it would be amazing  if this could be fixed.

It's suggested in #209 that this is fixed in the v4 branch, however I tried installing v4 via `yarn add 'NaturalIntelligence/fast-xml-parser#v4'` and running with `preserveOrder: true`, unfortunately I cannot see a change of behaviour.

Is there something I'm missing?

**Comment by amitguptagwl** [comment]
finally done in v4 using `preserveOrder` option
