### ISSUE TITLE
Remove post install?

### ISSUE THREAD

**Issue by svrooij** [NaturalIntelligence/fast-xml-parser#236]
I like fast-xml-parser, it works great!! But can you please remove the [postinstall](https://github.com/NaturalIntelligence/fast-xml-parser/blob/master/tasks/postinstall.js). It's also sending out a message when people install my [sonos-lib](https://github.com/svrooij/node-sonos-ts).

You can also use the [funding](https://docs.npmjs.com/configuring-npm/package-json.html#funding) in the **package.json** to complish the same. Then users can even use `npm fund fast-xml-parser` to open the funding info in the browser.

**Comment by amitguptagwl** [comment]
The purpose of post-install is not only for funding but to let people know about my other open source projects and attract contribution in terms of effort, not money. However, I'll check what appropriate can be done. Thanks

**Comment by omkadiri** [comment]
Am not sure why but it looks like the postInstall is causing aws codebuild failure for my project using custom bash build script with set -e

Working fine on my mac

**Comment by jpike88** [comment]
+1 to removing postinstall, I appreciate your work but like my install logs to be just install logs

**Comment by G-Rath** [comment]
I'd like to see the postinstall script removed too - if someone is interested in contributing, they'll seek out projects to contribute to.

`package.json` already contains fields for holding this sort of information as well - as already mentioned, the [`funding`](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#funding) field would be a great place to put this as it would let users who want to contribute do `npm fund fast-xml-parser` if they're wanting to contribute, without adding extra noise to build logs.

Another great place to put it would be the [contributor fields](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#people-fields-author-contributors), where you can put your name and url (arguably this is more semantically correct then using `fund`, since your url isn't for funding, but I'm not fussed on which you use).

I'm not against you wanting to make your url known for contributors - I just find the use of `postinstall` for this very obnoxious as there's no way to stop it from *anything* to the log since `npm` & co always print out info about what they're doing, even if your script does a check for an env variable to control if it should print:

```
❯ npm i @aws-sdk/client-s3

> fast-xml-parser@3.17.5 postinstall /project/node_modules/fast-xml-parser
> node tasks/postinstall.js || exit 0

Love fast-xml-parser? Check https://amitkumargupta.work for more projects and contribution.
```

**Comment by svrooij** [comment]
@G-Rath I already mentioned the funding part in the initial message.

Maybe we should create a fork just to remove the funding.

**Comment by G-Rath** [comment]
@svrooij I don't think forking is the right answer, not if it can be helped - that would split the community, and undermine @amitguptagwl's work.

I'd say we should create a PR actually removing the postinstall to close this issue, and give some time for people to respond (it is coming up to xmas after all, so people are probably on break/holiday).

**Comment by svrooij** [comment]
I don't want to fork the code, just to remove some annoying post install for my end users.

@amitguptagwl would you consider creating a github sponsor account and remove the funding post-install once you reach x amount of monthly sponsors?
