### ISSUE TITLE
why a separate getTraversalObj()?

### ISSUE THREAD

**Issue by mskadu** [NaturalIntelligence/fast-xml-parser#243]
Hi,

My first issue here. So hello all and kudos for the the excellent work being done here!

I am here with a question. I have been wondering about this code sample in [fast-xml-parser/master/README.md](https://github.com/NaturalIntelligence/fast-xml-parser/blob/master/README.md)
```
// Intermediate obj
var tObj = parser.getTraversalObj(xmlData,options);
var jsonObj = parser.convertToJson(tObj,options);
```
Is there any particular reason why getTraversalObj is called separately? Is there any sort of manipulation I can do with tObj before passing it convertToJson()? 

The reason I ask is that I am using your rather excellent parser to manipulate some a very large data set (millions) of XML files - each file of which is quite hefty (approx. avg of 8 megs). And I am fishing for opportunities to squeeze more performance out of my use of this library. I was hoping if I can manipulate the tObj instead of the jsonObj, I _could_ potentially make some savings there?

And if there isnt, is it worth considering moving that call to somewhere inside of the convertToJson() method?

Thanks in advance!

**Comment by amitguptagwl** [comment]
Thanks for your appreciation. This library is more useful when you use it in browser or when you need more parsing options. If you're parsing big files then some native python/c++ based parser may fit better.

This library first parse XML in an intermediate object and then create a JS object from intermediate object. It helps when you've to convert XML into other format like [nimn](https://nimn.in) or yaml without converting to refined JS object.

I'm working on FXP v4 keeping the big files in mind. But, due to the lack of time I'm not able to complete it.

**Comment by mskadu** [comment]
Thanks for your reply. Can you provide a sample if how this intermediate object can be traversed? Most conventional methods I am aware of e.g. `tObj['ElementName']` or `tObj.getChild(0)`, etc do not work.

Thanks.

**Comment by amitguptagwl** [comment]
You'll find the following properties;

1. tagname
2. parent
3. child: Either an array of objects of the same type or an object with property child tag's name.
4. attrsMap
5. val

You should be able to get this detail after debugging.

**Comment by amitguptagwl** [comment]
Let me know if we need to keep this issue open or if you have more queries.
