### ISSUE TITLE
"<" and ">" characters in values are no longer encoded

### ISSUE THREAD

**Issue by makromat** [NaturalIntelligence/fast-xml-parser#44]
Hi There,
I installed your package recently and I noticed something has changed. some html characters are no longer encoded. Is there way how to enable it again? 
Thanks

**Comment by amitguptagwl** [comment]
@makromat I would appreciate if you can fill the checklist while raising the issue or at least provide the necessary information as per the checklist.

**Comment by makromat** [comment]
@amitguptagwl sorry what checklist do you mean?

**Comment by amitguptagwl** [comment]
When you raise an issue, github shows you a default template which renders like this when you submit the issue.

### Checklist

* [ ] Are you running the latest version?
* [ ] Include sample input XML 
* [ ] Include actual output
* [ ] Include expected output
* [ ] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?
* [ ] Did you [star](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) the repository for further updates? ;)

However, I have just launched v3. I believe you would be interested to use the latest version. Please check the README as well.

**Comment by Delagen** [comment]
@makromat decodeHTMLchar:false by default, so all must work now with 3.0 version

**Comment by amitguptagwl** [comment]
@makromat, I believe you are using FXP 2.9.4 where decoding HTML entities was by default as expected in most of the scenarios. However, considering the need of different users there is an option provided in v3 to enable/disable it. 

As @Delagen suggested, if you move to the latest version i.e. v3, it should solve your problem as "decodeHTMLchar:false" is default setting. Otherwise as requested, sharing input, output and expected XML can help us better to assist your concern.

**Comment by amitguptagwl** [comment]
closing as no response. @makromat feel free to reopen if your issue still persist.
