### ISSUE TITLE
`allowBooleanAttributes` doesn't remember `true` as value of attribute

### ISSUE THREAD

**Issue by UltraCakeBakery** [NaturalIntelligence/fast-xml-parser#460]
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description
It seems that when using `allowBooleanAttributes` it mistakes any attribute with a value of `true` as a boolean attribute, though it is not a boolean attribute. 

I need to be able to include the original `true` value back when building my modified parsed xml.

### Input
```html
<test name="test" value="test"></test>
```

### Code
```js
import fs from 'fs'
import { XMLParser, XMLBuilder } from 'fast-xml-parser'

const html = fs.readFileSync( './test.html' )

const config = {
    ignoreAttributes: false,
    allowBooleanAttributes: true,
    attributeNamePrefix: '',
    attributesGroupName: "@",
    reserveOrder: true
}

const parser = new XMLParser({ ...config });
let jObj = parser.parse(html);

delete config.preserveOrder

const builder = new XMLBuilder({ ...config });
const xmlContent = builder.build(jObj);

console.log( xmlContent )
```

### Output
```
<test name="test" value></test>
```

### expected data
```
<test name="test" value="true"></test>
```

**Would you like to work on this issue?**

- [ ] Yes
- [x] No

**Comment by amitguptagwl** [comment]
This is working fine for me without changing anything in your code and config. So can you please check which version of FXP you're using and try it with online test tool as well.

**Comment by tkow** [comment]
I reproduce it, and [UltraCakeBakery](https://github.com/UltraCakeBakery) may miss true as test. In addition, allowBooleanAttributes are not related to this because it is option preserves have no value attribute.

If it input 
```html
<div a="1" b="true"></div>
```
and

```ts
import fs from 'fs'
import { XMLParser, XMLBuilder } from 'fast-xml-parser'

const html = fs.readFileSync( './test.html' )

const config = {
    ignoreAttributes: false,
    attributeNamePrefix: '',
    attributesGroupName: "@",
    reserveOrder: true
}

const parser = new XMLParser({ ...config });
let jObj = parser.parse(html);

const builder = new XMLBuilder({ ...config });
const xmlContent = builder.build(jObj);

console.log( xmlContent )
```

<img width="154" alt="スクリーンショット 2022-07-14 10 43 28" src="https://user-images.githubusercontent.com/7004725/178869247-d9c721be-e7d5-4b6c-9600-1982fa7aca48.png">

This is output, and this omit true attribute value "true" and boolean format.
My library version is  "fast-xml-parser": "4.0.9".
 It sometimes causes  bug when you need true as string value. Xml library occasionally have this case as I saw epub metadata layout value needs content true attribute as string.

**Comment by tkow** [comment]
@UltraCakeBakery @amitguptagwl 
This can avoid by
suppressBooleanAttributes: true
option, but this option all boolean values are converted to explicit value such as value="true" even if specifies parseAttributeValue: true nevertheless it can tell booleanAttribute and string attributes.
It is possible that remains <div a b="true"> </div> as parsed result?

**Comment by amitguptagwl** [comment]
just for quick answer, you can use relevant value processor.
