### ISSUE TITLE
Regex Injection Via Doctype Entities

### ISSUE THREAD

**Issue by ankitdn** [NaturalIntelligence/fast-xml-parser#628]
**Describe the bug**
While scanning my React Native application's manifest file using Vulert for vulnerability checks, I identified an issue associated with your package.

**Reference**
Upon conducting a vulnerability scan, the following references were identified:
Vulert Scan Report: [Vulert Report](https://vulert.com/vuln-scan/list/2a02a6f8-c9a5-4526-a1f1-d85faf95d9ac)
CVE Reference: [CVE-2023-34104](https://vulert.com/vuln-db/CVE-2023-34104)

**Comment by amitguptagwl** [comment]
Please upgrade to the latest version and confirm.

**Comment by AnkitVachhani** [comment]
Thank you! Working with the latest version.

**Comment by ankitdn** [comment]
Thank you! Working with latest version.

**Comment by levpachmanov** [comment]
Hi @amitguptagwl ,
I believe the affected versions listed in the [advisory](https://github.com/NaturalIntelligence/fast-xml-parser/security/advisories/GHSA-6w63-h3fj-q4vw) are incorrect. Can you please update it to affect 4.1.3 and above?

Up until version 4.1.2, the entity name is parsed using `RegExp("^\\s([a-zA-z0-0]+)[ \t](['\"])([^&]+)\\2");` - see https://github.com/NaturalIntelligence/fast-xml-parser/blob/v4.1.2/src/xmlparser/DocTypeReader.js#L108C35-L108C45
In this implementation, the entity name regex is constructed as follows ```RegExp( `&${match[1]};`,"g"),```. Since `match[1]` is `[a-zA-z0-0]+`. It is not possible to construct a vulnerable regular expression.
Starting 4.1.3, the implementation changes to the following vulnerable implementation - https://github.com/NaturalIntelligence/fast-xml-parser/blob/v4.1.3/src/xmlparser/DocTypeReader.js#L62  .

Notice that the [global](https://github.com/advisories/GHSA-6w63-h3fj-q4vw) advisory was already updated.
