### ISSUE TITLE
attribute value is parsed into different value

### ISSUE THREAD

**Issue by zeng450026937** [NaturalIntelligence/fast-xml-parser#98]
### Input

Set parseAttributeValue to be true

### Code

```js
if (val.trim() === "" || isNaN(val)) {
      val = val === "true" ? true : val === "false" ? false : val;
} else {
      if (val.indexOf(".") !== -1) {
         val = Number.parseFloat(val);
      } else {
         val = Number.parseInt(val, 10);
      }
}
return val;
```

### Output

For xml's attr value like '0001' will be parsed in to number 1

### Expect

Keep the attr value as ‘0001’

**Comment by amitguptagwl** [comment]
@zeng450026937 Can you please share sample XML and expected XML with configuration you are using? 

What I can understand is, you want string `"0001"` to be parsed as string `"0001"` but string `"1"` as number `1`.

Please let me know if my understanding is correct.

**Comment by zeng450026937** [comment]
Yes, your understanding is right.

**Comment by amitguptagwl** [comment]
This situation is not handled yet. What can we do is in this situation

1. if a string starts with 0 and has no decimal point then treat it as string. Otherwise continue with the current code

I would appreciate if you raise a PR for this small change to get it done fast. Otherwise I'll it in few days.

Thanks
